---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-9.1.17.0
  - jruby-9.2.5.0
  - jruby-head
  - ruby-head
  - truffleruby
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: truffleruby
before_install:
  - gem install bundler -v '2.0.1'
  - bundle config specific_platform true
before_script:
  - mysql -e 'create database hanami_id_test;'
  - psql -c 'create database hanami_id_test;' -U postgres
addons:
  postgresql: "9.6"
services:
  - postgresql
